config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root 'welcome#index'

  resources :users, only: [:index, :show]

  get 'static_page/landing_page'
  #get 'static_page/privacy_policy'
  get "privacy_polecy", to: "static_page#privacy_policy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    root_path 
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def landing_page
  end

  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserAdminApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation'%>
    <div class="container mt-4">
      <%= render 'shared/flash'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info mb-4 mt4">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning mb-4 mt-4">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">User Admin</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active"%> 
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Acount <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item"%>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete , class: "dropdown-item"%>
            </ul>
          </li>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link"%>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link"%>
        <% end%>
      </ul>
    </div>
  </div>
</nav>

app/views/static_page/landing_page.html.erb
<h1>StaticPage#landing_page</h1>
<p>Find me in app/views/static_page/landing_page.html.erb</p>

app/views/static_page/privacy_policy.html.erb
<h1>StaticPage#privacy_policy</h1>
<p>Find me in app/views/static_page/privacy_policy.html.erb</p>

app/views/users/_user.html.erb
<b>Id:</b>
<%= link_to user.id, user_path(user) %>
<br>
<b>Email:</b>
<%= user.email %>
<br>
<b>Confirmation:</b>
<%= user.confirmed? %>
<br>
<b><%= "sign_in_count".humanize %>: </b>        
<%= user.sign_in_count %>
<br>
<b><%= "current_sign_in_at".humanize %>:</b>
<%= user.current_sign_in_at %>
<br>
<b><%= "last_sign_in_at".humanize %>:</b>
<%= user.last_sign_in_at %>
<br>
<b><%= "current_sign_in_ip".humanize %>:</b>
<%= user.current_sign_in_ip %>
<br>
<b><%= "last_sign_in_ip".humanize %>:</b>
<%= user.last_sign_in_ip %>

app/views/users/index.html.erb
<h2>All Users</h2>
<% @users.each do |user| %>
  <hr>
  <%= render 'users/user', user: user%>
<% end %>

app/views/users/show.html.erb
<%= render 'users/user', user: @user %>
<br>
<%= link_to "All Users", users_path %>

app/views/welcome/index.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <i class="fas fa-home"></i>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<div>

</div>